spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://comment-service-database:5432/comment_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka
server:
  port: 8082
<<<<<<< HEAD
=======
>>>>>>> 2aeceb63e7eca8d97efb42db83645d13c3e176cd
