spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://commentservicedatabase:5432/comment_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
server:
  port: 8082
