spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://commentservicedatabase:5432/comment_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka
server:
  port: 8082

  eureka.client.service-url.defaultZone=http://eurekaserver:8070/eureka/