spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://commentservicedatabase:5432/comment_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = {cipher}cf18b43ed79ced5bb517db33956cf60f9a0250038ce22c67edc625c77b594766
spring.jpa.hibernate.ddl-auto=create
hibernate.show_sql=true