spring.jpa.database=postgresql
spring.datasource.url=jdbc:postgresql://postservicedatabase:5432/post_service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username = postgres
spring.datasource.password = {cipher}f98324a8ac3909da3e4cdc8b7db190fa628b2a62b9da0c225e65759050c672e1
spring.jpa.hibernate.ddl-auto=create
hibernate.show_sql=true