spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:postgresql://postservicedatabase:5432/post_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka
      
server:
  port: 8081
